data:
  star_dir: /lustre/work/YukaYamada/data/PFS/s23-colorterm/star/tract ##Directory path for the downloaded HSC stars
  random_dir_masked: /lustre/work/jingjing.shi/pfs-LSS/random/HSC_random/database_fail_fcfd_quality_mask/s23-colorterm/tracts ##Directory path for the downloaded HSC randoms
  random_dir: /lustre/work/jingjing.shi/pfs-LSS/random/HSC_random/database/s23-colorterm/tracts
  target_file: /lustre/work/YukaYamada/data/PFS/test/pfs-ssp-co/s23b_ssp_co_targets.fits ##path to the pfs co targets (output of pfstarget)
  patchqa_dir: /lustre/work/YukaYamada/data/PFS/s23-colorterm/patchqa ##Directory path for the downloaded HSC patchqa

bsmask:
  star_bsmask: /lustre/work/YukaYamada/data/PFS/s23-colorterm/bsmask/star
  random_bsmask: /lustre/work/YukaYamada/data/PFS/s23-colorterm/bsmask/random
  target_bsmask: /lustre/work/YukaYamada/data/PFS/test/pfs-ssp-co #path to the target bright star mask
  
bgmask:
  star_bgmask: /lustre/work/YukaYamada/data/PFS/s23-colorterm/bgmask/star
  random_bgmask: /lustre/work/YukaYamada/data/PFS/s23-colorterm/bgmask/random
  target_bgmask: /lustre/work/YukaYamada/data/PFS/test/pfs-ssp-co #path to the target bright star mask
 
Gaia:
    bs: /lustre/work/YukaYamada/data/Gaia/bsmask
    star: /lustre/work/YukaYamada/data/Gaia/star ##Directory path for the downloaded Gaia stars

out_dir:
  imaging: /lustre/work/YukaYamada/data/PFS/output/imaging #Directory path for the imaging properties
  optuna: /lustre/work/YukaYamada/data/PFS/output/optuna #Directory path for the optuna output
  weights: /lustre/work/YukaYamada/data/PFS/output/weights #Directory path to store the imaging systematic weights
  
tractlist: /home/YukaYamada/repository/PFS/pfstarget/bin/hsc/sql/TractInfoS23.csv